controller:
  replicaCount: 2
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"

defaultBackend:
  enabled: true
